### PR TITLE
Fix XSS in Handling Text Block.

### PR DESCRIPTION
**Pull request by roman-mibex-2**
Before: The notebook renderer allowed XSS attack via a 'text/plain' output element.
Example attack:

```
{
  "cells": [{
    "cell_type": "code",
    "source": [],
    "outputs": [{
      "output_type": "display_data",
      "data": {
        "text/plain": "<img src onerror=\"alert('XSS at '+origin)\">"
      }
    }]
  }]
}
```

### CODE REVIEW

**Comment by jsvine** [comment]
Many thanks for catching that, @roman-mibex-2. Merging.

**Comment by roman-mibex-2** [comment]
Thanks for the quick merge.

PS: I've still two other security relevant PS out there from August.

**Comment by jsvine** [comment]
Yep, should now be handled and available on `master` and in v0.8.0. Thanks again!

**Comment by roman-mibex-2** [comment]
Hmm...I think I didn't get it quite right. If there is angle breakets in the text output, you would expect to see it and not be stripped / interpreted as HTML.
There will be a follow-up PR.

**Pull request merged**
