### PR TITLE
Switch To escapeHTML for text-output

### PR DESCRIPTION
**Pull request by roman-mibex-2**
For text output you expect the raw text.
For example, an output like
<result> should return that text,
and not be interpreted as HTML

### CODE REVIEW

**Comment by roman-mibex-2** [comment]
Example:

```
          "data": {
            "text/plain": [
              "<open file '<fdopen>', mode 'rb' at 0x10a4be660>"
            ]
          },
```

Before: The <open> etc got dropped / or miss-interpreted as HTML.

Now: It is rendered:
image

**Comment by jsvine** [comment]
Hi @roman-mibex-2, and thanks. Just to make sure that this is really what we want, would you be able to provide some demo notebooks and before/after screenshots?

**Comment by roman-mibex-2** [comment]
Demo Notebook where I've noticed it first:

https://gist.github.com/roman-mibex-2/baa669f1ac0c8bbff03a9cee5ee4f074

Input/Output Number 10

**Comment by jsvine** [comment]
Thanks — now merged and in v0.8.1

**Pull request merged**
