### PR TITLE
Add support for a custom highlighter function.

### PR DESCRIPTION
**Pull request by bradhowes**
Existing code works fine when Prismjs is run in a browser to colorize code.
However, for static site builders such as Metalsmith, we would like to not
rely on browser Javascript. Setting an appropriate highlighter method on a
notebookjs object allows us to continue the rendering process using Prismjs
to highlight code and error cells and save the resulting HTML to a file.

### CODE REVIEW

**Comment by jsvine** [comment]
Thanks, @bradhowes! This seems like a useful feature. Would you be able to share a reproducible repository/zipfile demonstrating the intended usage?

**Comment by bradhowes** [comment]
Thanks @jsvine. I've created a demo repo at https://github.com/bradhowes/notebookjs-highliter
The README also has links to my blog where it is being put to good use.

**Comment by jsvine** [comment]
Many thanks, @bradhowes. Looks great, and works for me. Merging.

**Comment by jsvine** [comment]
Now available in v0.3.1, on `master` and via NPM.

**Comment by bradhowes** [comment]
Great. Thanks for the merge!

**Pull request merged**
